### ISSUE TITLE
Name missing from credits

### ISSUE THREAD

**Issue by marcbotham** [NERC-CEH/hornet-watch-app#37]
Need to add Didier Descouens (Muséum de Toulouse) to the credits. This is the author of the cut-out image on the flash page. I wonder whether the copyright with his name could be on the flash as well given that this is the first image everyone is guaranteed to see?

**Comment by kazlauskis** [comment]
Hi, I wouldn't put the credits on the splash screen, it contains a lot of information already. Best to have it somewhere where people have more than 2sec to read.
